<a href="https://colab.research.google.com/github/Yogen4/Workshop.ai/blob/main/Week8(Workshop8)TextPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import re
def remove_urls(text):
  """
  This function will try to remove URL present in out dataset and replace it with space using regex library.
  Input Args:
  text: strings of text that may contain URLs.
  Output Args:
  text: URLs replaces with text
  """
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

In [ ]:
text = " Hello, Click on this link to open facebook https://www.facebook.com/"
text_url = remove_urls(text)
print("Original:", text)
print("After removing URL:", text_url)

Original:  Hello, Click on this link to open facebook https://www.facebook.com/
After removing URL:  Hello, Click on this link to open facebook

In [ ]:
import pandas as pd

# Load dataset (CHANGE PATH if needed)
df_text = pd.read_csv("/content/trumptweets_small.csv")

# Check column names
print("Columns:", df_text.columns)

# Automatically pick correct text column
if "content" in df_text.columns:
    text_col = "content"
elif "text" in df_text.columns:
    text_col = "text"
else:
    raise ValueError("No suitable text column found!")

# Remove URLs (also handle missing values)
text_no_url = df_text[text_col].dropna().apply(remove_urls)

# Show result (for demonstration)
print("\nOriginal:", df_text[text_col].iloc[0])
print("After URL removal:", text_no_url.iloc[0])

Columns: Index(['id', 'link', 'content', 'date', 'retweets', 'favorites', 'mentions',
       'hashtags', 'geo'],
      dtype='object')

Original: Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!
After URL removal: Be sure to tune in and watch Donald Trump on Late Night with David Letterman as he presents the Top Ten List tonight!

In [ ]:
text_no_url

0        Be sure to tune in and watch Donald Trump on L...
1        Donald Trump will be appearing on The View tom...
2        Donald Trump reads Top Ten Financial Tips on L...
3        New Blog Post: Celebrity Apprentice Finale and...
4        "My persona will never be that of a wallflower...
                               ...
41117    I have never seen the Republican Party as Stro...
41118    Now Mini Mike Bloomberg is critical of Jack Wi...
41119    I was thrilled to be back in the Great State o...
41120    “In the House, the President got less due proc...
41121    A great show! Check it out tonight at 9pm. @ F...
Name: content, Length: 41122, dtype: object

In [ ]:
def remove_emoji(string):
    if not isinstance(string, str):
        return ""

    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"
                               u"\U0001F300-\U0001F5FF"
                               u"\U0001F680-\U0001F6FF"
                               u"\U0001F1E0-\U0001F1FF"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               "]+", flags=re.UNICODE)

    return emoji_pattern.sub(r' ', string)

In [ ]:
test_string = "Hello @siman 👋🏾, still on up for the movie???  #MovieNight #friday #🍱"
no_emoji = remove_emoji(test_string)
no_emoji

'Hello @siman  , still on up for the movie???  #MovieNight #friday # '

In [ ]:
def removeunwanted_characters(document):
    """
    Removes mentions, hashtags, punctuation, emojis, and extra spaces.
    """

    if not isinstance(document, str):
        return ""

    # remove emojis first
    document = remove_emoji(document)

    # remove user mentions (@username)
    document = re.sub(r"@[A-Za-z0-9_]+", " ", document)

    # remove hashtags (#word → word removed)
    document = re.sub(r"#[A-Za-z0-9_]+", " ", document)

    # remove punctuation & special characters
    document = re.sub(r"[^0-9A-Za-z ]", " ", document)

    # remove multiple spaces
    document = re.sub(r"\s+", " ", document)

    return document.strip()

In [ ]:
# Test:
cleaned_string = removeunwanted_characters(test_string)
cleaned_string

'Hello still on up for the movie'

In [ ]:
text_removed_unwanted = df_text["content"].apply(removeunwanted_characters)
text_removed_unwanted

0        Be sure to tune in and watch Donald Trump on L...
1        Donald Trump will be appearing on The View tom...
2        Donald Trump reads Top Ten Financial Tips on L...
3        New Blog Post Celebrity Apprentice Finale and ...
4        My persona will never be that of a wallflower ...
                               ...
41117    I have never seen the Republican Party as Stro...
41118    Now Mini Mike Bloomberg is critical of Jack Wi...
41119    I was thrilled to be back in the Great State o...
41120    In the House the President got less due proces...
41121    A great show Check it out tonight at 9pm FoxNe...
Name: content, Length: 41122, dtype: object

In [ ]:
import nltk

# Install correct tokenizer
nltk.download('punkt')

# OPTIONAL: also install this (sometimes needed)
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
# Test case:
IN = "He did not try to navigate after the first bold flight, for the reaction had taken something out of his soul."
OUT = word_tokenize(IN)
print("Input:", IN)
print("Tokens:", OUT)

Input: He did not try to navigate after the first bold flight, for the reaction had taken something out of his soul.
Tokens: ['He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the', 'first', 'bold', 'flight', ',', 'for', 'the', 'reaction', 'had', 'taken', 'something', 'out', 'of', 'his', 'soul', '.']

In [ ]:
from nltk.tokenize import RegexpTokenizer

def remove_punct(text):
    """
    Removes punctuation from text (works for both string and token list)
    """
    tokenizer = RegexpTokenizer(r"\w+")

    # If input is list → join into string
    if isinstance(text, list):
        text = ' '.join(text)

    # Tokenize without punctuation
    clean_tokens = tokenizer.tokenize(text)

    return clean_tokens

In [ ]:
#Test
text_punctutation = "He did not try to navigate: after the!!!! first bold flight, for,,,,, the reaction!!!!had taken??????? something out of his soul."
text_punc_token = word_tokenize(text_punctutation)
print(text_punctutation)
print("+++++++++++++++++_____________________+++++++++++++++++++++")
print(text_punc_token)
print("_____________________+++++++++++++++++++++++++++__________________")
text_clean = remove_punct(text_punc_token)
print(text_clean)

He did not try to navigate: after the!!!! first bold flight, for,,,,, the reaction!!!!had taken??????? something out of his soul.
+++++++++++++++++_____________________+++++++++++++++++++++
['He', 'did', 'not', 'try', 'to', 'navigate', ':', 'after', 'the', '!', '!', '!', '!', 'first', 'bold', 'flight', ',', 'for', ',', ',', ',', ',', ',', 'the', 'reaction', '!', '!', '!', '!', 'had', 'taken', '?', '?', '?', '?', '?', '?', '?', 'something', 'out', 'of', 'his', 'soul', '.']
_____________________+++++++++++++++++++++++++++__________________
['He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the', 'first', 'bold', 'flight', 'for', 'the', 'reaction', 'had', 'taken', 'something', 'out', 'of', 'his', 'soul']

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = set(stopwords.words('english'))
custom_stopwords = ['@', 'RT']
stop_words.update(custom_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:

def remove_stopwords(text_tokens):
  """
  This function removes all the stopwords present in out text tokens.
  Input Args:
  text_tokens: tokenize input of our datasets.
  Returns:
  result_tokens: list of token without stopword.
  """

  result_tokens = []
  for token in text_tokens:
    if token not in stop_words:
       result_tokens.append(token)
  return result_tokens

In [ ]:
test_inputs = ['He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the', 'first', 'bold', 'flight', ',', 'for', 'the', 'reaction', 'had', 'taken', 'something', 'out', 'of', 'his', 'soul', '.']
print(test_inputs)
tokens_without_stopwords = remove_stopwords(test_inputs)
print(tokens_without_stopwords)

['He', 'did', 'not', 'try', 'to', 'navigate', 'after', 'the', 'first', 'bold', 'flight', ',', 'for', 'the', 'reaction', 'had', 'taken', 'something', 'out', 'of', 'his', 'soul', '.']
['He', 'try', 'navigate', 'first', 'bold', 'flight', ',', 'reaction', 'taken', 'something', 'soul', '.']

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

def lemmatization(token_text):
  """
  This function performs the lemmatization operations as explained above.
  Input Args:
  token_text: list of tokens.
  Returns:
  lemmatized_tokens: list of lemmatized tokens.
  """
  lemma_tokens = []
  wordnet = WordNetLemmatizer()
  lemmatized_tokens = [wordnet.lemmatize(token, pos = 'v') for token in token_text]

  return lemmatized_tokens

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
lemmatization("Should we go walking or swimming".split())

['Should', 'we', 'go', 'walk', 'or', 'swim']

In [ ]:
from nltk.stem import PorterStemmer

def stemming(text):
  """
  This function performs stemming operations.
  Input Args:
  token_text: list of tokenize text.
  Returns:
  stemm_tokes: list of stemmed tokens.
  """
  porter = PorterStemmer()
  stemm_tokens = []
  for word in text:
    stemm_tokens.append(porter.stem(word))
  return stemm_tokens

In [ ]:
#Test
print("+++++++++++++++++++++++++++++++" "INPUT TOKENS" "++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
token_text_test=['Connects','Connecting','Connections','Connected','Connection','Connectings','Connect']
print(token_text_test)
print("++++++++++++++++++" "LEMMATIZED TOKENS" "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
lemma_tokens = lemmatization(token_text_test)
print(lemma_tokens)
print("+++++++++++++++++++++" "STEMMED TOKENS" "+++++++++++++++++++++++++++++++++++++")
stemmed_tokens = stemming(token_text_test)
print(stemmed_tokens)

+++++++++++++++++++++++++++++++INPUT TOKENS++++++++++++++++++++++++++++++++++++++++++++++++++++++++
['Connects', 'Connecting', 'Connections', 'Connected', 'Connection', 'Connectings', 'Connect']
++++++++++++++++++LEMMATIZED TOKENS+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
['Connects', 'Connecting', 'Connections', 'Connected', 'Connection', 'Connectings', 'Connect']
+++++++++++++++++++++STEMMED TOKENS+++++++++++++++++++++++++++++++++++++
['connect', 'connect', 'connect', 'connect', 'connect', 'connect', 'connect']

In [ ]:
def lower_order(text):
  """
  This function converts all the text in input text to lower order.
  Input Args:
  token_text : input text.
  Returns:
  small_order_text : text converted to small/lower order.
  """
  small_order_text = text.lower()
  return small_order_text

# Test:
sample_text = "This Is some Normalized TEXT"
sample_small = lower_order(sample_text)
print(sample_small)

this is some normalized text

In [ ]:
data = pd.read_csv("/content/trum_tweet_sentiment_analysis.csv", encoding="ISO-8859-1")
data.head()

                                                text  Sentiment
0  RT @JohnLeguizamo: #trump not draining swamp b...        0.0
1  ICYMI: Hackers Rig FM Radio Stations To Play A...        0.0
2  Trump protests: LGBTQ rally in New York https:...        1.0
3  "Hi I'm Piers Morgan. David Beckham is awful b...        0.0
4  RT @GlennFranco68: Tech Firm Suing BuzzFeed fo...        0.0

In [ ]:
data_cleaning = data["text"].dropna()

In [ ]:
data_cleaning[0]

'RT @JohnLeguizamo: #trump not draining swamp but our taxpayer dollars on his trips to advertise his properties! @realDonaldTrumpÂ\x85 https://t.co/gFBvUkMX9z'

In [ ]:
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import word_tokenize

def text_cleaning_pipeline(text, rule="lemmatize"):
    """
    Complete text preprocessing pipeline
    """

    # 1. Lowercase
    text = lower_order(text)

    # 2. Remove URLs
    text = remove_urls(text)

    # 3. Remove emojis
    text = remove_emoji(text)

    # 4. Remove unwanted characters
    text = removeunwanted_characters(text)

    # 5. Tokenization
    tokens = word_tokenize(text)

    # 6. Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # 7. Lemmatization / Stemming
    wordnet = WordNetLemmatizer()
    porter = PorterStemmer()

    if rule == "lemmatize":
        tokens = [wordnet.lemmatize(word, pos='v') for word in tokens]

    elif rule == "stem":
        tokens = [porter.stem(word) for word in tokens]

    else:
        print("Pick between lemmatize or stem")

    # 8. Join tokens back
    return " ".join(tokens)

In [ ]:
sample = "Hello @gabe_flomo 👋🏾, I still want us to hit that new sushi spot??? LMK when you're free cuz I can't go this or next weekend since I'll be swimming!!! #sushiBros #rawFish #🍱"
print(text_cleaning_pipeline(sample))

hello still want us hit new sushi spot lmk free cuz go next weekend since swim

In [ ]:
test = data["text"][0]

In [ ]:
print(text_cleaning_pipeline(test))

rt drain swamp taxpayer dollars trip advertise properties

In [ ]:
cleaned_tokens = data["text"].apply(lambda dataset: text_cleaning_pipeline(dataset))